apiVersion: v1
kind: Pod
metadata:
  name: client-pod
spec:
  containers:
  - name: client
    image: nginx
    command: ["/bin/sh"]
    args: ["-c", "while true; do curl -X GET http://load-balancer-pod:80; sleep 5; done"]
