apiVersion: v1
kind: Pod
metadata:
  name: load-balancer-pod
  labels:
    app: nginx-load-balancer
spec:
  containers:
    - name: nginx-load-balancer
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
      securityContext:
        capabilities:
          drop:
            - ALL
      env:
        - name: AUTH_TOKEN
          value: "QY!&+Qxr2ucy3M.m6|)vCWA&2BCqYq{7"
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo 'HTTP/1.1 200 OK\n\nHello, world!' | nc -l -p 80; done"]

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  selector:
    app: nginx-load-balancer
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  

