apiVersion: v1
kind: Pod
metadata:
  name: proxy-pod
spec:
  containers:
  - name: nginx-proxy
    image: nginx
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 0 
      capabilities:
        add:
        - SYS_PTRACE 

